// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.intera.shoprecommender;

import com.intera.shoprecommender.Item;

privileged aspect Item_Roo_JavaBean {
    
    public String Item.getItemName() {
        return this.itemName;
    }
    
    public void Item.setItemName(String itemName) {
        this.itemName = itemName;
    }
    
}
