// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.intera.shoprecommender;

import com.intera.shoprecommender.Purchase;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Purchase_Roo_Configurable {
    
    declare @type: Purchase: @Configurable;
    
}
