// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.intera.shoprecommender;

import com.intera.shoprecommender.Shopper;

privileged aspect Shopper_Roo_JavaBean {
    
    public String Shopper.getUsername() {
        return this.username;
    }
    
    public void Shopper.setUsername(String username) {
        this.username = username;
    }
    
}
