// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.intera.shoprecommender;

import com.intera.shoprecommender.Shopper;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Shopper_Roo_Configurable {
    
    declare @type: Shopper: @Configurable;
    
}
